In [1]:
import csv
import nfl_data_py as nfl
import pandas as pd

In [4]:
# Loading the file in 

file_path = ("Resources/clean_nfl_data.csv")
df = pd.read_csv(file_path)
df = pd.DataFrame(df)

df.head()

,Unnamed: 0,play_id,home_team,away_team,season_type,week,posteam,posteam_type,defteam,side_of_field,...,jersey_number,id,qb_epa,xyac_epa,xyac_mean_yardage,xyac_median_yardage,xyac_success,xyac_fd,xpass,pass_oe
0,2,55,TEN,ARI,REG,1,TEN,home,ARI,TEN,...,22.0,00-0032764,-1.399805,NaN,NaN,NaN,NaN,NaN,0.491433,-49.143300
1,3,76,TEN,ARI,REG,1,TEN,home,ARI,TEN,...,17.0,00-0029701,0.032412,1.165133,5.803177,4.0,0.896654,0.125098,0.697346,30.265415
2,4,100,TEN,ARI,REG,1,TEN,home,ARI,TEN,...,17.0,00-0029701,-1.532898,0.256036,4.147637,2.0,0.965009,0.965009,0.978253,2.174652
3,6,152,TEN,ARI,REG,1,ARI,away,TEN,ARI,...,1.0,00-0035228,2.692890,0.567838,7.420427,4.0,1.000000,1.000000,0.458989,54.101130
4,7,181,TEN,ARI,REG,1,ARI,away,TEN,TEN,...,1.0,00-0035228,-1.009908,NaN,NaN,NaN,NaN,NaN,0.419833,-41.983326